#!/usr/bin/env python

import sys
import os
from argparse import ArgumentParser


try:
    import pygtk
    pygtk.require('2.0')
except:
    print 'You need PyGTK version 2 or higher!'
    sys.exit(1)

try:
    import gtk
    import gtk.glade
except:
    print 'You need the Python Glade interface!'
    sys.exit(1)

try:
    import cairo
except:
    print 'You need the Python Cairo interface!'
    sys.exit(1)


app_home_dir = os.getcwd()
#print 'App home dir = '+app_home_dir
sys.path.append(os.path.join(app_home_dir, 'src'))

def run_gui(filename=None):
    from quill.gui.app import Application
    app = Application(app_home_dir, filename)
    gtk.main()


description = """
    Quill is an open-source handwriting note-taking app for Android
    tablets. This program is a desktop companion for it. It lets you
    view ``.quill`` backup files without your Android device, and/or
    convert them to different formats."""



if __name__ == '__main__':
    
    parser = ArgumentParser(description=description)
    parser.add_argument('input',
                        help='input file name', default=None, nargs='?')
    parser.add_argument('output',
                        help='output file name', default=None, nargs='?')
    parser.add_argument('-p, --page', dest='page', action='store',
                        default=None, type=int,
                        help='page number to export (default: all pages)')
    parser.add_argument('--gui', dest='gui', action='store_true',
                        default=False, 
                        help='start the gui')
    args = parser.parse_args()
    
    if args.input is not None and args.output is not None:
        from quill.converter import QuillConverter
        QuillConverter(args.input, args.output).run(args.page)

    if args.gui:
        run_gui(args.input)




