#!/usr/bin/env python

import sys
import os

try:
    import quill
except ImportError:
    app_home_dir = os.getcwd()
    sys.path.append(os.path.join(app_home_dir, 'src'))
    import quill


if __name__ == '__main__':
    from quill.cmdline import launch
    launch()
    


